<script data-cfasync="false" src="../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js')}}"></script>')}}"<script src="{{asset('frontend/js/jquery.js')}}"></script>')}}"
<script src="{{asset('frontend/js/popper.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/bootstrap.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/jquery.magnific-popup.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/owl.carousel.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/moment.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/jquery.sticky-kit.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/jquery.easy-ticker.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/jquery.subscribe-better.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/theia-sticky-sidebar.min.js')}}"></script>')}}"
<script src="{{asset('frontend/js/main.js')}}"></script>')}}"
<script src="{{asset('frontend/js/switcher.js')}}"></script>')}}"
